name: Auto Update
on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set SSH Environment
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

    - name: Spider WeChat Account and Update repo.
      run: |
        pip install fake_useragent requests
        git clone https://github.com/SWHL/AI-Competition-Collections.git
        cd AI-Competition-Collections/scripts
        python spider_wechat_account.py --fake_id "MzIwNDA5NDYzNA==" --cookie ${WECHAT_COOKIE} --token ${WECHAT_TOKEN}
        
        git config --global user.name "SWHL"
        git config --global user.email "liekkaskono@163.com"
        git remote remove origin
        git remote add origin git@github.com:SWHL/OnlyPaddleOCR.git
        
        git add .
        git commit -m 'actions auto update'
        git push -f origin main